file = open("rosalind_dna.txt", 'r')

sequence = "GTTAGGCCCTCGGGCGACTAACAGGGTCCGATAGGAACAGATCCATGCACCCCGTGAAAACATCCTTATCCAGACTAATTTCTCGTGATTTAGACCGTTGTTGGTTGTCAAACGTAGAGCGAGACTCCAGTATGATCTTTCAATAGAACTCGACTTCGCCCTTCCTGAAGCTAGTCCGCACTCTGGGATCAGGTGTCCGTACAGTCGGCCAGGTAGTTCGTTATCAGTAGAACAGCCTGGGGTCAATCTAAGTCTACGGCTGCAAACAGCTCCGAGAAAAACGTCATAGCTGCTGAGGGAAGACGTGGTAACCTCAGTATACGTACAAGGGCGTAACCGTAGGAGCATGCATTCTACTCAGGCCGAGATTTGGCGGGTACTCGTCGTTCGCGTGAATGCCGCGAGTTTCGGTCGTCTGCGACCTTCGGTGTGGGTGCCACTACCAAATTCTTGGAGGTCAATGTATGGCATTTAGTTCCTGGGTTACCGTCTATCTCGGATTATGCTGGTGAGCAGTAGGAGCTACACGGTTCTCTCCTGGATCTCTCGCATAGCTGCCATTTGGTAGTGAGCACCATAATAACGCTTCATGCGGACCGCTCACGTACCCAGCATGATTTAGGTTGAGTTAGCTCTCGATCCCCAATTCCCCAGGACAACACCTCTATTTCACAGCTGACTACCAGTCCACGACTACTCCGCTAACTATACAGCCCTCGCCTCTGTGATCTGCTTCAACAGATTATAGTTCAGGCACAAAGAGACAAATTTCTTGGTACACAGCTTATCCGGACTTACAGACAGACATGCCCCGTTAAACGGCACACACCAGTCTCTTAGAGTCATGCGCCAGAGCCAGAGCCAGTCACACAAGTTGGCCGGTCTGGGATGCCGGAGGAAATCCAGTTAGGGGTAGCTTGAAAGACCATATGCTACA"
sequence2 = file.read()
print(sequence)
print(sequence2)
A = 0
T = 0
C = 0
G = 0

for c in sequence:
    if c == 'A':
        A += 1
    elif c == 'T':
        T += 1
    elif c == 'C':
        C += 1
    else:
        G += 1

print(str(A) + ' ' + str(C) + ' ' + str(G) + ' ' + str(T))

A2 = 0
T2 = 0
C2 = 0
G2 = 0

for c in sequence2:
    if c == 'A':
        A2 += 1
    elif c == 'T':
        T2 += 1
    elif c == 'C':
        C2 += 1
    else:
        G2 += 1
print(str(A2) + ' ' + str(C2) + ' ' + str(G2) + ' ' + str(T2))