file = open('rosalind_revc.txt', 'r')
sequence = "TGCGCATTCTAAGTGGGTTACCCTTTCGCCACGGAATTTGCAGAGTGAACGGAGGCCCTATCCTCGTTAATAGCCTTGATTATCCAGAAGTTTGGACGGCGGATAGCGGCTCGTAGCGTTATTGACGGAAAGTATTGAAATCTGTAGGGTGGGAGGAGAACGGGAGAATCCTCTTGCATACCTTAACAATATCCATCTTATTCTTTTGGTGCCTCTGTTTACCCTTTGGAATCTTGCCAATGCCCCATAACACATCACAGTCCTGACCGTCTCAAACTCGGTTCTATAATCGGGTCGATGCAGATGGCTTTCGTCCAGCTTCTTCCGAAAACACTAGGGGCTGATCCGTGCACAACAACTTTTCCCGGGTGTATCAAATAATCGTGGTTCTTGAGAGTGCAAGGCGTGGAGAAAAAATTGGGGCCCTGATGTGTGTAACTCCGGATTATAACTGGGCTCGAGACCAACACCTACGATTGAATCTCTATCCTCGGCGTGAAAGTATGCTACATCTTCCAGAACCCCCGGCATATGATCGGGCTGGTTATGATTGGTCTCCTTAATGCTCATCGTACCGCCTATCCCCGGAAGCAGTCAACGGTAGTGCTGGGTGGGATGCAGGTGAGAACTAGATTGTGACCGTACCACGAACTGAGCGGAGAATTGCGACATATACAAGTTGCAACACGTACTGGTATAGAGCACTCTAAAGGAACGAGTGCTGTCTCCAGAAGAAGAACAAGTCTTTAAATTCCTGATTGCAGAGCCCTTATTATTGTTCTATCAGACACAGATGTTATGTCACCTGTTGTTGAGGTATTTCCGAGCGCTGTAGCTGTAATCGGGACTGGCCGCACCTCGCGGGCCCTTGGGATTATATCACACCATCTCACTATCACCA"

compliment = []

for c in sequence:
    if c == 'A':
        compliment.append('T')
    elif c == 'T':
        compliment.append('A')
    elif c == 'C':
        compliment.append('G')
    else:
        compliment.append('C')

print(compliment)
compliment.reverse()
reverse_compliment = ''.join(compliment)
print(reverse_compliment)

