# Rosalind problem 9
# Finding a motif in DNA

def findMotif():
    dna = 'TTTGACTACGTTCGACTACGGACTACGGACTACGATTCAGACTACGGACTACGTCGTGCCTGACTACGGTGACTACGTGACTACGTGACTACGCTGACTACGGACTACGTTCTCGACTACGGACTACGCGACTACGGGACTACGGACTACGAGAGACTACGTTGGACTACGAGCCGACTACGGACTACGGACTACGTCTTCTATCGTGCTTAGACTGACTACGTTGACTACGAGGACTACGAGGACTACGGCCGACTACGCGACTACGGACTACGAGATTGTGTGACTACGTGACTACGTACGACTACGGCAGACTACGGGGGACTACGGACTACGGACTACGAGGAGAGACTACGTAAGTTTACGACTACGGAGGACAGTGTGGACTACGGGACTACGGACTACGTGTTTGACTACGGTGCGGACTACGCAGTAGTGATGCTGGTTGACTACGCTGACTACGGGGAACTGCGTACTGACTACGGGAGTTGACTACGCGAAGCAATGTCGACTACGGGGTGACTACGGTGACTACGGACTACGTTGACTACGAGACTACGGACTACGGACTACGGACTACGGACTACGACGACTACGTTGTTGGACTACGGACTACGCGACTACGTGTATATAGCAGACTACGGACTACGCTGACTACGTTGCGACTACGGACTACGGACTACGAGGCTGACTACGGTTGCAATGACTACGGACTACGTGGCCAACTCCAGACTACGAGACTACGGATGACTACGGACTACGTGACTACGCGCGATATGATCCGGGACTACGGACTACGATGAGAGACTACGACCAGATTGACTACGAGAGAGGACTACGGACTACGGACTACGGGGGACTACGACGACTACGCAGACTACGGACTACGTGGACTACGGACTACGCACTCGGACTACGAAGACTACGGCGACTACGGTAGACTACGTAGGGACTACGTTACCAGACTACGTAAGGTGACTACGCTTCTTA'
    dna_list = [c for c in dna]
    motif = 'GACTACGGA'
    first_motif_base = motif[0]
    positions = []
    i = 0

    for base in dna_list:
        if base == first_motif_base:
            location = i + 1
            motif_in_seq = i + (len(motif))
            if dna[i:motif_in_seq] == motif:
                positions.append(str(location))
        i += 1
    print(' '.join(positions))

findMotif()